import { useEffect, useMemo, useState } from 'react'
import type { ChangeEvent, FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { toast } from 'sonner'
import { ArrowLeft, ArrowRight, CheckCircle2, UploadCloud } from 'lucide-react'
import { Footer, PageShell, SiteHeader } from '../components/Layout'
import { Badge } from '../components/UI'
import { advancedFeatures, featureOptions, pageOptions, serviceInterestOptions } from '../data/demoData'
import { useAuth } from '../lib/auth'
import { loadDraft, saveDraft, submitApplication, uploadApplicationFiles } from '../lib/platformService'
import type { ApplicationDraft } from '../types/platform'

const steps = ['Applicant', 'Business', 'Website', 'Content', 'Services', 'Agreement', 'Confirmation']
const requiredAgreements = ['I understand the free website has a defined scope.', 'I understand that premium features may require payment.', 'I agree to provide content and feedback on time.', 'I understand that delays in providing content may affect my queue position.', 'I agree to the terms and privacy policy.', 'I confirm that the information submitted is accurate.']
const consents = ['I agree to receive project updates by email.', 'I agree to receive project updates by text message.', 'I would like to receive information about optional business services.']

function TextField({ label, name, value, onChange, type = 'text', required = false }: { label: string; name: keyof ApplicationDraft; value: unknown; onChange: (name: keyof ApplicationDraft, value: unknown) => void; type?: string; required?: boolean }) {
  return <label className="block text-sm font-semibold text-slate-800">{label}<input type={type} required={required} value={String(value ?? '')} onChange={(e) => onChange(name, e.target.value)} className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 outline-none focus:border-royal-600 focus:ring-4 focus:ring-blue-100" /></label>
}
function TextArea({ label, name, value, onChange, required = false }: { label: string; name: keyof ApplicationDraft; value: unknown; onChange: (name: keyof ApplicationDraft, value: unknown) => void; required?: boolean }) { return <label className="block text-sm font-semibold text-slate-800">{label}<textarea required={required} value={String(value ?? '')} onChange={(e) => onChange(name, e.target.value)} rows={4} className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 outline-none focus:border-royal-600 focus:ring-4 focus:ring-blue-100" /></label> }
function SelectField({ label, name, value, onChange, options }: { label: string; name: keyof ApplicationDraft; value: unknown; onChange: (name: keyof ApplicationDraft, value: unknown) => void; options: string[] }) { return <label className="block text-sm font-semibold text-slate-800">{label}<select value={String(value ?? '')} onChange={(e) => onChange(name, e.target.value)} className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3"><option value="">Select</option>{options.map((option) => <option key={option}>{option}</option>)}</select></label> }
function CheckGrid({ options, selected = [], onToggle }: { options: string[]; selected?: string[]; onToggle: (value: string) => void }) { return <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{options.map((option) => <button type="button" key={option} onClick={() => onToggle(option)} className={`rounded-2xl border px-4 py-3 text-left text-sm ${selected.includes(option) ? 'border-royal-600 bg-blue-50 text-royal-700' : 'bg-white'}`}>{option}{advancedFeatures.includes(option) && <span className="ml-2 text-xs text-amber-600">Upgrade</span>}</button>)}</div> }

export function ApplicationForm() {
  const { user, profile } = useAuth()
  const [step, setStep] = useState(0)
  const [draft, setDraft] = useState<ApplicationDraft>(() => loadDraft())
  const [files, setFiles] = useState<FileList | null>(null)
  const [result, setResult] = useState<{ applicationNumber: string; queuePosition: number; estimatedReviewTime: string } | null>(null)
  const progress = useMemo(() => Math.round(((step + 1) / steps.length) * 100), [step])

  useEffect(() => {
    if (profile && !draft.email) setDraft((current) => ({ ...current, full_name: profile.full_name, email: profile.email, phone: profile.phone }))
  }, [profile, draft.email])
  useEffect(() => { saveDraft(draft) }, [draft])

  function update(name: keyof ApplicationDraft, value: unknown) { setDraft((current) => ({ ...current, [name]: value })) }
  function toggleArray(name: keyof ApplicationDraft, value: string) { const current = (draft[name] as string[]) || []; update(name, current.includes(value) ? current.filter((item) => item !== value) : [...current, value]) }
  async function finish(event: FormEvent) {
    event.preventDefault()
    try {
      await uploadApplicationFiles(files, user?.id || 'local-demo-user')
      const submitted = await submitApplication(draft, user?.id)
      setResult({ applicationNumber: submitted.application.application_number, queuePosition: submitted.queuePosition, estimatedReviewTime: submitted.estimatedReviewTime })
      setStep(6)
      toast.success('Your application has been received')
    } catch (error) { toast.error(error instanceof Error ? error.message : 'Could not submit application') }
  }

  return <PageShell><SiteHeader /><main className="bg-cloud-50 px-4 py-10 sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl"><Link to="/" className="mb-6 inline-flex items-center gap-2 text-sm font-semibold text-royal-700"><ArrowLeft size={16} /> Back to home</Link><div className="rounded-[2rem] bg-white p-5 shadow-2xl sm:p-8"><div className="mb-8"><Badge tone="gold">Autosaves on every change</Badge><h1 className="mt-4 text-3xl font-bold text-navy-950 sm:text-5xl">Apply for My Free Website</h1><p className="mt-3 text-slate-600">Complete the application in approximately five minutes. Purchases are not required to apply.</p><div className="mt-6 h-3 rounded-full bg-cloud-100"><div className="h-3 rounded-full bg-royal-600 transition-all" style={{ width: `${progress}%` }} /></div><div className="mt-3 flex flex-wrap gap-2">{steps.map((label, index) => <button key={label} onClick={() => index < 6 && setStep(index)} className={`rounded-full px-3 py-1 text-xs ${index === step ? 'bg-navy-950 text-white' : 'bg-cloud-100'}`}>{index + 1}. {label}</button>)}</div></div>
      <form onSubmit={finish}>
        {step === 0 && <div className="grid gap-4 sm:grid-cols-2"><TextField label="Full name" name="full_name" value={draft.full_name} onChange={update} required /><TextField label="Email address" name="email" value={draft.email} onChange={update} type="email" required /><TextField label="Phone number" name="phone" value={draft.phone} onChange={update} /><SelectField label="Preferred contact method" name="preferred_contact_method" value={draft.preferred_contact_method} onChange={update} options={['Email', 'Phone', 'Text message']} /><TextField label="City" name="city" value={draft.city} onChange={update} /><TextField label="State" name="state" value={draft.state} onChange={update} /><TextField label="Country" name="country" value={draft.country} onChange={update} /><TextField label="Time zone" name="timezone" value={draft.timezone} onChange={update} /></div>}
        {step === 1 && <div className="grid gap-4"><div className="grid gap-4 sm:grid-cols-2"><TextField label="Business name" name="business_name" value={draft.business_name} onChange={update} required /><TextField label="Business category" name="category" value={draft.category} onChange={update} /><TextField label="Year established" name="year_established" value={draft.year_established} onChange={update} /><TextField label="Number of employees" name="employee_count" value={draft.employee_count} onChange={update} /></div><TextArea label="Business description" name="description" value={draft.description} onChange={update} required /><TextArea label="Target customer" name="target_customer" value={draft.target_customer} onChange={update} /><div className="grid gap-4 sm:grid-cols-2"><TextField label="Service area" name="service_area" value={draft.service_area} onChange={update} /><TextField label="Current website URL" name="current_website" value={draft.current_website} onChange={update} /><TextField label="Google Business Profile URL" name="google_business_url" value={draft.google_business_url} onChange={update} /></div><TextArea label="Social media links" name="social_links" value={draft.social_links} onChange={update} /></div>}
        {step === 2 && <div className="grid gap-6"><div className="grid gap-4 sm:grid-cols-2"><TextField label="Type of website needed" name="website_type" value={draft.website_type} onChange={update} /><TextField label="Primary goal of website" name="primary_goal" value={draft.primary_goal} onChange={update} /><TextField label="Website style preference" name="style_preferences" value={draft.style_preferences} onChange={update} /><TextField label="Color preferences" name="color_preferences" value={draft.color_preferences} onChange={update} /><TextField label="Desired domain" name="desired_domain" value={draft.desired_domain} onChange={update} /><TextField label="Existing domain" name="existing_domain" value={draft.existing_domain} onChange={update} /><TextField label="Existing hosting provider" name="hosting_provider" value={draft.hosting_provider} onChange={update} /><SelectField label="Estimated launch urgency" name="urgency" value={draft.urgency} onChange={update} options={['Standard', 'Soon', 'Immediate']} /></div><TextArea label="Competitor or inspiration websites" name="inspiration_urls" value={draft.inspiration_urls} onChange={update} /><div><p className="mb-3 font-semibold">Requested pages</p><CheckGrid options={pageOptions} selected={draft.requested_pages} onToggle={(value) => toggleArray('requested_pages', value)} /></div><div><p className="mb-3 font-semibold">Required features</p><CheckGrid options={featureOptions} selected={draft.requested_features} onToggle={(value) => toggleArray('requested_features', value)} /></div></div>}
        {step === 3 && <div className="grid gap-6"><div className="grid gap-4 sm:grid-cols-3"><SelectField label="Do you already have a logo?" name="logo_ready" value={draft.logo_ready} onChange={update} options={['Yes', 'No', 'Need help']} /><SelectField label="Do you have professional business photos?" name="photos_ready" value={draft.photos_ready} onChange={update} options={['Yes', 'No', 'Need help']} /><SelectField label="Is your written website content ready?" name="content_ready" value={draft.content_ready} onChange={update} options={['Yes', 'No', 'Partially']} /><SelectField label="Do you need copywriting assistance?" name="copywriting_needed" value={draft.copywriting_needed} onChange={update} options={['Yes', 'No', 'Not sure']} /><SelectField label="Do you need a new logo?" name="need_logo" value={draft.need_logo} onChange={update} options={['Yes', 'No', 'Not sure']} /><SelectField label="Do you need professional graphics?" name="need_graphics" value={draft.need_graphics} onChange={update} options={['Yes', 'No', 'Not sure']} /></div><label className="flex cursor-pointer flex-col items-center rounded-3xl border border-dashed border-slate-300 bg-cloud-50 p-8 text-center"><UploadCloud className="text-royal-700" size={36} /><span className="mt-3 font-semibold">Upload logo, photos, service list, menu, brochure, brand guide, written content, or other files</span><input multiple type="file" onChange={(event: ChangeEvent<HTMLInputElement>) => setFiles(event.target.files)} className="mt-4" /></label>{files && <p className="text-sm text-slate-600">{files.length} file(s) selected for upload.</p>}</div>}
        {step === 4 && <div><p className="mb-4 text-slate-600">Choose any optional services you may be interested in. These are not required to apply for the free website.</p><CheckGrid options={serviceInterestOptions} selected={draft.service_interests} onToggle={(value) => toggleArray('service_interests', value)} /></div>}
        {step === 5 && <div className="grid gap-6"><div><h3 className="text-xl font-bold text-navy-950">Agreement</h3><div className="mt-4 grid gap-3">{requiredAgreements.map((item) => <label key={item} className="flex gap-3 rounded-2xl border p-4 text-sm"><input type="checkbox" checked={(draft.agreements || []).includes(item)} onChange={() => toggleArray('agreements', item)} required />{item}</label>)}</div></div><div><h3 className="text-xl font-bold text-navy-950">Optional Consent</h3><div className="mt-4 grid gap-3">{consents.map((item) => <label key={item} className="flex gap-3 rounded-2xl border p-4 text-sm"><input type="checkbox" checked={(draft.consents || []).includes(item)} onChange={() => toggleArray('consents', item)} />{item}</label>)}</div></div></div>}
        {step === 6 && result && <div className="rounded-3xl bg-emerald-50 p-8 text-center"><CheckCircle2 className="mx-auto text-emerald-600" size={52} /><h2 className="mt-4 text-3xl font-bold text-navy-950">Your Application Has Been Received!</h2><div className="mt-6 grid gap-4 sm:grid-cols-4"><div className="rounded-2xl bg-white p-4"><p className="text-xs text-slate-500">Application number</p><p className="font-bold">{result.applicationNumber}</p></div><div className="rounded-2xl bg-white p-4"><p className="text-xs text-slate-500">Initial queue position</p><p className="font-bold">#{result.queuePosition}</p></div><div className="rounded-2xl bg-white p-4"><p className="text-xs text-slate-500">Status</p><p className="font-bold">Application Submitted</p></div><div className="rounded-2xl bg-white p-4"><p className="text-xs text-slate-500">Estimated review</p><p className="font-bold">{result.estimatedReviewTime}</p></div></div><Link to="/dashboard" className="mt-8 inline-flex rounded-full bg-navy-950 px-6 py-3 font-bold text-white">Create Account or Access Dashboard</Link></div>}
        {step < 6 && <div className="mt-8 flex justify-between gap-3"><button type="button" onClick={() => setStep(Math.max(0, step - 1))} className="rounded-full border px-5 py-3">Back</button>{step < 5 ? <button type="button" onClick={() => setStep(step + 1)} className="inline-flex items-center gap-2 rounded-full bg-navy-950 px-5 py-3 font-bold text-white">Continue <ArrowRight size={16} /></button> : <button className="rounded-full bg-royal-600 px-5 py-3 font-bold text-white">Submit Application</button>}</div>}
      </form></div></div></main><Footer /></PageShell>
}
