import { useEffect, useMemo, useState } from 'react'
import type { ChangeEvent, FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { toast } from 'sonner'
import { ArrowLeft, ArrowRight, CheckCircle2, ClipboardList, UploadCloud } from 'lucide-react'
import { Footer, PageShell, SiteHeader } from '../components/Layout'
import { Badge } from '../components/UI'
import { advancedFeatures, featureOptions, pageOptions, serviceInterestOptions } from '../data/demoData'
import { useAuth } from '../lib/auth'
import { loadDraft, saveDraft, submitApplication, uploadApplicationFiles } from '../lib/platformService'
import type { ApplicationDraft } from '../types/platform'

const steps = ['Contact Information', 'Business Information', 'Website Goals', 'Launch Readiness', 'Offer Acknowledgment', 'Review and Submit']
const requiredAgreements = ['I understand the standard design and initial build have no upfront website design fee for approved applicants.', 'I understand managed hosting with Business Launch Initiative is required for launch at $34/month because every live website needs hosting.', 'I understand domain registration, premium tools, advanced features, and custom functionality may cost extra.', 'I agree to provide accurate content, business information, and feedback promptly.', 'I understand the included scope has limits.', 'I understand approval is not guaranteed.']
const consents = ['I agree to receive project updates by email.', 'I agree to receive project updates by text message.', 'I would like to receive information about optional business services.']
const buildOptions = ['Standard Website Build', 'Priority Website Build', 'Business Growth Plan', 'Custom Software Consultation', 'Not sure yet']

function TextField({ label, name, value, onChange, type = 'text', required = false }: { label: string; name: keyof ApplicationDraft; value: unknown; onChange: (name: keyof ApplicationDraft, value: unknown) => void; type?: string; required?: boolean }) {
  return <label className="block text-sm font-semibold text-slate-800">{label}<input type={type} required={required} value={String(value ?? '')} onChange={(e) => onChange(name, e.target.value)} className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 outline-none focus:border-royal-600 focus:ring-4 focus:ring-blue-100" /></label>
}
function TextArea({ label, name, value, onChange, required = false, rows = 4 }: { label: string; name: keyof ApplicationDraft; value: unknown; onChange: (name: keyof ApplicationDraft, value: unknown) => void; required?: boolean; rows?: number }) { return <label className="block text-sm font-semibold text-slate-800">{label}<textarea required={required} value={String(value ?? '')} onChange={(e) => onChange(name, e.target.value)} rows={rows} className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 outline-none focus:border-royal-600 focus:ring-4 focus:ring-blue-100" /></label> }
function SelectField({ label, name, value, onChange, options, required = false }: { label: string; name: keyof ApplicationDraft; value: unknown; onChange: (name: keyof ApplicationDraft, value: unknown) => void; options: string[]; required?: boolean }) { return <label className="block text-sm font-semibold text-slate-800">{label}<select required={required} value={String(value ?? '')} onChange={(e) => onChange(name, e.target.value)} className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 outline-none focus:border-royal-600 focus:ring-4 focus:ring-blue-100"><option value="">Select</option>{options.map((option) => <option key={option}>{option}</option>)}</select></label> }
function CheckGrid({ options, selected = [], onToggle }: { options: string[]; selected?: string[]; onToggle: (value: string) => void }) { return <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{options.map((option) => <button type="button" key={option} onClick={() => onToggle(option)} className={`rounded-2xl border px-4 py-3 text-left text-sm ${selected.includes(option) ? 'border-royal-600 bg-blue-50 text-royal-700' : 'bg-white'}`}>{option}{advancedFeatures.includes(option) && <span className="ml-2 text-xs text-amber-600">Upgrade</span>}</button>)}</div> }
function SummaryItem({ label, value }: { label: string; value?: unknown }) {
  const display = Array.isArray(value) ? value.join(', ') : String(value ?? '')
  return <div className="rounded-2xl bg-cloud-50 p-4"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">{label}</p><p className="mt-2 text-sm font-semibold text-navy-950">{display || 'Not provided'}</p></div>
}

export function ApplicationForm() {
  const { user, profile } = useAuth()
  const [step, setStep] = useState(0)
  const [draft, setDraft] = useState<ApplicationDraft>(() => loadDraft())
  const [files, setFiles] = useState<FileList | null>(null)
  const [result, setResult] = useState<{ applicationNumber: string; estimatedReviewTime: string } | null>(null)
  const [errors, setErrors] = useState<string[]>([])
  const [submitting, setSubmitting] = useState(false)
  const progress = useMemo(() => result ? 100 : Math.round(((step + 1) / steps.length) * 100), [result, step])

  useEffect(() => {
    if (profile && !draft.email) setDraft((current) => ({ ...current, full_name: profile.full_name, email: profile.email, phone: profile.phone }))
  }, [profile, draft.email])
  useEffect(() => { saveDraft(draft) }, [draft])

  function update(name: keyof ApplicationDraft, value: unknown) { setDraft((current) => ({ ...current, [name]: value })) }
  function toggleArray(name: keyof ApplicationDraft, value: string) { const current = (draft[name] as string[]) || []; update(name, current.includes(value) ? current.filter((item) => item !== value) : [...current, value]) }
  function hasValue(name: keyof ApplicationDraft) {
    const value = draft[name]
    return Array.isArray(value) ? value.length > 0 : Boolean(String(value ?? '').trim())
  }
  function validateCurrentStep() {
    const requiredByStep: Record<number, [keyof ApplicationDraft, string][]> = {
      0: [['full_name', 'Full name'], ['email', 'Email address'], ['phone', 'Phone number'], ['preferred_contact_method', 'Preferred contact method']],
      1: [['business_name', 'Business name'], ['category', 'Industry'], ['city', 'City'], ['state', 'State'], ['service_area', 'Service area']],
      2: [['primary_goal', 'Primary website goal'], ['description', 'Services or products offered'], ['target_customer', 'Target customer'], ['requested_pages', 'Desired pages']],
      3: [['logo_ready', 'Logo readiness'], ['photos_ready', 'Photo readiness'], ['content_ready', 'Written content readiness'], ['ready_30_days', 'Launch readiness'], ['authorized_decision_maker', 'Decision authority'], ['build_option_interest', 'Build option interest']],
    }
    const nextErrors = (requiredByStep[step] ?? []).filter(([name]) => !hasValue(name)).map(([, label]) => `${label} is required.`)
    if (step === 0 && draft.email && !String(draft.email).includes('@')) nextErrors.push('Enter a valid email address.')
    if (step === 4) {
      const missingAgreements = requiredAgreements.filter((item) => !(draft.agreements || []).includes(item))
      if (missingAgreements.length) nextErrors.push('Please acknowledge each required offer disclosure.')
    }
    setErrors(nextErrors)
    return nextErrors.length === 0
  }
  function continueToNextStep() {
    if (!validateCurrentStep()) return
    setStep((current) => Math.min(steps.length - 1, current + 1))
    setErrors([])
  }
  async function finish(event: FormEvent) {
    event.preventDefault()
    if (!validateCurrentStep()) return
    setSubmitting(true)
    try {
      await uploadApplicationFiles(files, user?.id || 'local-demo-user')
      const submitted = await submitApplication(draft, user?.id)
      setResult({ applicationNumber: submitted.application.application_number, estimatedReviewTime: submitted.estimatedReviewTime })
      toast.success('Your application has been received')
    } catch (error) { toast.error(error instanceof Error ? error.message : 'Could not submit application') } finally { setSubmitting(false) }
  }

  return <PageShell><SiteHeader /><main className="bg-cloud-50 px-4 py-10 sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl"><Link to="/" className="mb-6 inline-flex items-center gap-2 text-sm font-semibold text-royal-700"><ArrowLeft size={16} /> Back to home</Link><div className="rounded-[2rem] bg-white p-5 shadow-2xl sm:p-8"><div className="mb-8"><Badge tone="gold">Guided business launch application</Badge><h1 className="mt-4 text-3xl font-bold text-navy-950 sm:text-5xl">Start My Business Launch Application</h1><p className="mt-3 text-slate-700">Tell us about your business, launch readiness, and website goals. Your draft autosaves on this device; signed-in applicants can continue with the same account in future portal updates.</p><div className="mt-6 h-3 rounded-full bg-cloud-100"><div className="h-3 rounded-full bg-royal-600 transition-all" style={{ width: `${progress}%` }} /></div><div className="mt-3 flex flex-wrap gap-2">{steps.map((label, index) => <button type="button" key={label} onClick={() => { setStep(index); setErrors([]) }} className={`rounded-full px-3 py-1 text-xs ${index === step ? 'bg-navy-950 text-white' : 'bg-cloud-100'}`}>{index + 1}. {label}</button>)}</div></div>
      {errors.length > 0 && <div className="mb-6 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><p className="font-bold">Please review the following:</p><ul className="mt-2 list-disc pl-5">{errors.map((error) => <li key={error}>{error}</li>)}</ul></div>}
      {result && <div className="rounded-3xl bg-emerald-50 p-8 text-center"><CheckCircle2 className="mx-auto text-emerald-600" size={52} /><h2 className="mt-4 text-3xl font-bold text-navy-950">Application Received</h2><p className="mx-auto mt-3 max-w-2xl text-slate-700">Thank you for applying to the Business Launch Initiative. Our team will review your business information and contact you regarding eligibility and available launch options.</p><div className="mt-6 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-white p-4"><p className="text-xs text-slate-500">Reference number</p><p className="font-bold">{result.applicationNumber}</p></div><div className="rounded-2xl bg-white p-4"><p className="text-xs text-slate-500">Status</p><p className="font-bold">Application Submitted</p></div><div className="rounded-2xl bg-white p-4"><p className="text-xs text-slate-500">Review window</p><p className="font-bold">{result.estimatedReviewTime}</p></div></div><div className="mt-6 rounded-2xl bg-white p-5 text-left"><h3 className="font-bold text-navy-950">Next Steps</h3><ul className="mt-3 grid gap-2 text-sm text-slate-700"><li>Prepare your logo, photos, services, and contact information.</li><li>Watch for updates about eligibility and available launch options.</li><li>Sign in to monitor your application once your account is active.</li></ul></div><Link to={user ? '/dashboard' : '/auth'} className="mt-8 inline-flex rounded-full bg-navy-950 px-6 py-3 font-bold text-white">{user ? 'Open Dashboard' : 'Sign In to Monitor Application'}</Link></div>}
      {!result && <>
      <form onSubmit={finish}>
        {step === 0 && <div className="grid gap-4 sm:grid-cols-2"><TextField label="Full name" name="full_name" value={draft.full_name} onChange={update} required /><TextField label="Email address" name="email" value={draft.email} onChange={update} type="email" required /><TextField label="Phone number" name="phone" value={draft.phone} onChange={update} required /><SelectField label="Preferred contact method" name="preferred_contact_method" value={draft.preferred_contact_method} onChange={update} options={['Email', 'Phone', 'Text message']} required /></div>}
        {step === 1 && <div className="grid gap-4"><div className="grid gap-4 sm:grid-cols-2"><TextField label="Business name" name="business_name" value={draft.business_name} onChange={update} required /><TextField label="Industry" name="category" value={draft.category} onChange={update} required /><TextField label="City" name="city" value={draft.city} onChange={update} required /><TextField label="State" name="state" value={draft.state} onChange={update} required /><TextField label="Service area" name="service_area" value={draft.service_area} onChange={update} required /><TextField label="Years in business" name="year_established" value={draft.year_established} onChange={update} /></div><TextField label="Current website URL" name="current_website" value={draft.current_website} onChange={update} /><TextArea label="Social media links" name="social_links" value={draft.social_links} onChange={update} rows={3} /></div>}
        {step === 2 && <div className="grid gap-6"><div className="grid gap-4 sm:grid-cols-2"><TextField label="Primary website goal" name="primary_goal" value={draft.primary_goal} onChange={update} required /><TextField label="Type of website needed" name="website_type" value={draft.website_type} onChange={update} /><TextField label="Desired domain" name="desired_domain" value={draft.desired_domain} onChange={update} /><TextField label="Existing hosting provider" name="hosting_provider" value={draft.hosting_provider} onChange={update} /></div><TextArea label="Services or products offered" name="description" value={draft.description} onChange={update} required /><TextArea label="Target customer" name="target_customer" value={draft.target_customer} onChange={update} required /><TextArea label="Current marketing challenges" name="current_marketing_challenges" value={draft.current_marketing_challenges} onChange={update} /><TextArea label="Competitor or inspiration websites" name="inspiration_urls" value={draft.inspiration_urls} onChange={update} /><div><p className="mb-3 font-semibold">Desired pages</p><CheckGrid options={pageOptions} selected={draft.requested_pages} onToggle={(value) => toggleArray('requested_pages', value)} /></div><div><p className="mb-3 font-semibold">Required features</p><CheckGrid options={featureOptions} selected={draft.requested_features} onToggle={(value) => toggleArray('requested_features', value)} /></div></div>}
        {step === 3 && <div className="grid gap-6"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><SelectField label="Do you have a logo?" name="logo_ready" value={draft.logo_ready} onChange={update} options={['Yes', 'No', 'Need help']} required /><SelectField label="Do you have business photos?" name="photos_ready" value={draft.photos_ready} onChange={update} options={['Yes', 'No', 'Need help']} required /><SelectField label="Do you have written content?" name="content_ready" value={draft.content_ready} onChange={update} options={['Yes', 'No', 'Partially']} required /><SelectField label="Ready to begin within 30 days?" name="ready_30_days" value={draft.ready_30_days} onChange={update} options={['Yes', 'No', 'Not sure']} required /><SelectField label="Authorized to make decisions?" name="authorized_decision_maker" value={draft.authorized_decision_maker} onChange={update} options={['Yes', 'No']} required /><SelectField label="Which build option interests you?" name="build_option_interest" value={draft.build_option_interest} onChange={update} options={buildOptions} required /><SelectField label="Do you need copywriting assistance?" name="copywriting_needed" value={draft.copywriting_needed} onChange={update} options={['Yes', 'No', 'Not sure']} /><SelectField label="Do you need a new logo?" name="need_logo" value={draft.need_logo} onChange={update} options={['Yes', 'No', 'Not sure']} /><SelectField label="Do you need professional graphics?" name="need_graphics" value={draft.need_graphics} onChange={update} options={['Yes', 'No', 'Not sure']} /></div><label className="flex cursor-pointer flex-col items-center rounded-3xl border border-dashed border-slate-300 bg-cloud-50 p-8 text-center"><UploadCloud className="text-royal-700" size={36} /><span className="mt-3 font-semibold">Upload logo, photos, service list, menu, brochure, brand guide, written content, or other files</span><span className="mt-2 text-sm text-slate-600">Files remain private when Supabase storage is configured.</span><input multiple type="file" onChange={(event: ChangeEvent<HTMLInputElement>) => setFiles(event.target.files)} className="mt-4" /></label>{files && <p className="text-sm text-slate-600">{files.length} file(s) selected for upload.</p>}<div><p className="mb-4 text-slate-600">Optional growth services you may be interested in later. These are not required for application review.</p><CheckGrid options={serviceInterestOptions} selected={draft.service_interests} onToggle={(value) => toggleArray('service_interests', value)} /></div></div>}
        {step === 4 && <div className="grid gap-6"><div><h3 className="text-xl font-bold text-navy-950">Required Offer Acknowledgment</h3><div className="mt-4 grid gap-3">{requiredAgreements.map((item) => <label key={item} className="flex gap-3 rounded-2xl border p-4 text-sm leading-6"><input type="checkbox" checked={(draft.agreements || []).includes(item)} onChange={() => toggleArray('agreements', item)} required />{item}</label>)}</div></div><div><h3 className="text-xl font-bold text-navy-950">Optional Communication Consent</h3><div className="mt-4 grid gap-3">{consents.map((item) => <label key={item} className="flex gap-3 rounded-2xl border p-4 text-sm leading-6"><input type="checkbox" checked={(draft.consents || []).includes(item)} onChange={() => toggleArray('consents', item)} />{item}</label>)}</div></div></div>}
        {step === 5 && <div className="grid gap-6"><div className="rounded-3xl bg-navy-950 p-6 text-white"><ClipboardList className="mb-4 text-gold-500" /><h2 className="text-2xl font-bold">Review Before You Submit</h2><p className="mt-2 text-sm leading-6 text-slate-300">Confirm the information below is accurate. You can go back to any step before submitting.</p></div><div className="grid gap-4 md:grid-cols-2"><SummaryItem label="Applicant" value={draft.full_name} /><SummaryItem label="Email" value={draft.email} /><SummaryItem label="Business" value={draft.business_name} /><SummaryItem label="Industry" value={draft.category} /><SummaryItem label="Primary goal" value={draft.primary_goal} /><SummaryItem label="Build option interest" value={draft.build_option_interest} /><SummaryItem label="Desired pages" value={draft.requested_pages} /><SummaryItem label="Required features" value={draft.requested_features} /><SummaryItem label="Ready within 30 days" value={draft.ready_30_days} /><SummaryItem label="Files selected" value={files ? `${files.length} file(s)` : 'No files selected'} /></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950">Submitting this application does not guarantee approval. Our team will review fit, readiness, scope, and production capacity before confirming available launch options.</div></div>}
        <div className="mt-8 flex justify-between gap-3"><button type="button" onClick={() => { setStep(Math.max(0, step - 1)); setErrors([]) }} disabled={step === 0 || submitting} className="rounded-full border px-5 py-3 disabled:cursor-not-allowed disabled:opacity-50">Back</button>{step < steps.length - 1 ? <button type="button" onClick={continueToNextStep} className="inline-flex items-center gap-2 rounded-full bg-navy-950 px-5 py-3 font-bold text-white">Continue <ArrowRight size={16} /></button> : <button disabled={submitting} className="rounded-full bg-royal-600 px-5 py-3 font-bold text-white disabled:cursor-not-allowed disabled:opacity-60">{submitting ? 'Submitting...' : 'Submit Application'}</button>}</div>
      </form></>}</div></div></main><Footer /></PageShell>
}
